### PR TITLE
Fixes #14: Refactoring ray portable runner

### LINKED ISSUE #14: Support execution of Splittable DoFn without splitting
We have extensive tests to verify that we can execute DoFns that split (https://github.com/ray-project/ray_beam_runner/blob/master/ray_beam_runner/portability/ray_runner_test.py#L573-L608) and do SDK-side checkpointing.

We need to make sure this is supported. Please reach out to @pabloem  to check what's needed.

### PR DESCRIPTION
**Pull request by pabloem**
Making the code more readable and more efficient.

Also adding support for SDF-initiated checkpointing
- This is when a user DoFn returns before being completely finished to checkpoint current work.

### CODE REVIEW

**Comment by pabloem** [comment]
r: @iasoon ? : )

fyi @pdames @jjyao @wilsonwang371

**Comment by pabloem** [comment]
I realize that CI is broken. Should we fix it as part of this PR? or as a follow-up PR?

**Comment by pabloem** [comment]
I made all the portability runner tests run : )

**Comment by pabloem** [comment]
I created https://github.com/ray-project/ray_beam_runner/issues/28 and https://github.com/ray-project/ray_beam_runner/issues/29 to track fixing the comments in the PR. Maybe then we can merge to unblock other reviews? : )

**Comment by iasoon** [comment]
Sounds good to me :)

**Pull request merged**
