### PR TITLE
Ensuring tests can run without passing context around

### PR DESCRIPTION
**Pull request by pabloem**

### CODE REVIEW

**Comment by pabloem** [comment]
r: @pdames

**Comment by pabloem** [comment]
failures are from the normal flakiness which I'm investigating (fyi @iasoon)

**Review by iasoon — APPROVED** [review]
Changes look good to me!

It makes sense to me that we run the testcases in isolation, but we should remember that we didn't actually fix the resource leak with this :laughing: - so I think #35 should stay open if we merge this.

**Comment by pabloem** [comment]
right - that makes sense. I think this is just a first step to 'green-up' our tests : ) - I'll make sure #35 stays open

**Pull request merged**
